<div class="container">
	<ul class="thumbnails">
	<?php 
	foreach ($products as $product){
	?>
		<li class="span2">
			<div class="catThumbnail thumbnail">
				<img alt="<?php echo $product->getName(); ?>" style="width: 100px; height: 100px;" src="<?php echo $product->getImageName("small"); ?>">
				<div class="caption catCaption">
					<a href="index.php?s=product&p=<?php echo $product->getProductId(); ?>">
						<h4><?php echo $product->getName(); ?></h4>
					</a>
					<p><?php echo $product->getDescription("short"); ?></p>
				</div>
				<div class="caption">
				<a href="index.php?s=product&p=<?php echo $product->getProductId(); ?>" class="btn btn-primary catButton">More</a>
				</div>
			</div>
		</li>


	<?php
	}
	?>
	</ul>
</div>