<div class="container">
	<?php 
	foreach ($products as $product){
	?>
		<li class="span3">
			<div class="thumbnail">
				<img data-src="holder.js/300x200" alt="300x200" style="width: 300px; height: 200px;" src="">
				<div class="caption">
					<h3><?php echo $product->getName(); ?></h3>
					<p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
					<p><a href="#" class="btn btn-primary">Action</a> <a href="#" class="btn">Action</a></p>
				</div>
			</div>
		</li>


	<?php
	}
	?>
</div>