<div class="container">
	<?php 
		if ($uploadError == 1 || $uploadError == 2){
	?>					
		<div class="alert alert-error text-center">
			<strong>File is too large. Filesize must be under 2Mb</strong>
		</div>
	<?php 
		} elseif ($uploadError > 1 || !$uploadFileName){
	?>		
		<div class="alert alert-error text-center">
			<strong>File has not been uploaded</strong>
			<p>The system cannot upload your assignment. Please contact your course administrator.</p>
		</div>
	<?php 
		} else {
	?>
		<div class="alert alert-success text-center">
			<strong><?php echo $uploadFileName ?> has been uploaded</strong>
			<p>Hooray!</p>
		</div>
	<?php 
		}	
	?>
</div>

