<div class="container" id="mainContainer">
<img alt="Sweets Emporium" style="width: 500px;" src="public/img/m1.jpg">
	<a href="index.php?s=category&p=1" class="btn-large btn-primary">Lollies</a>
	<a href="index.php?s=category&p=2" class="btn-large btn-primary">Cakes</a>
	<a href="index.php?s=category&p=3" class="btn-large btn-primary">Muffins</a>
	<a href="index.php?s=category&p=4" class="btn-large btn-primary">Biscuits</a>

</div>

