<div class="container">
	<div class="span6">
		<h5 class="text-info">Login</h5>
		<form action="index.php" method="POST" name="login"
			class="form-horizontal system-login-form" id="login">
			<div class="control-group">
				<div class="input-prepend">
					<span class="add-on"><i class="icon-user"></i></span>
					<input name="studentID" type="text" placeholder="Student ID" class="span2" value="<?php echo $formStudentID; ?>">
				</div>
			</div>
			<div class="control-group">
				<div class="input-prepend">
					<span class="add-on"><i class="icon-lock"></i> </span>
					<input name="password" type="password" placeholder="Password" class="span2" value="">
				</div>
			</div>
			<input name="submit" type="submit" class="btn btn-primary" value="Login">
		</form>
	</div>
	<div class="span4">
	</div>	
</div>

