<div class="container" id="mainContainer">
	<?php if ($page=="cart"){ 
		$order = $cart;
		?>
		<h4 class="text-info">Shopping Cart</h4>
		<?php if($user){ ?>
			<a href="index.php?s=confirmOrder" class="btn-large btn-primary catButton">Confirm Order</a>
		<?php } else { ?>
			<a href="index.php?s=login" class="btn-large btn-primary catButton">Login to order</a>
		<?php } ?>
	<?php } else { ?>
		<h4 class="text-info">Order Detail</h4>
	<?php } ?>
	<?php if (!$order || !$order->getItemList()){ ?>
		<h5>No items to display</h5>	
	<?php } else { ?>
		<table class="table">
			<tr>
				<th></th>
				<th>Item</th>
				<th>Quantity</th>
				<th>Unit Price</th>
				<th class="price">Price</th>
				<th></th>
			</tr>
			<?php 
			foreach ($order->getItemList() as $orderItem){
			?>
			<tr>
				<td></td>
				<td><a href="index.php?s=product&amp;p=<?php echo $orderItem->getProductId(); ?>"><?php echo $orderItem->getProductName(); ?></a>
				<a href="index.php?s=removeItem&amp;p=<?php echo $orderItem->getProductId(); ?>" class="btn-mini btn-primary">remove</a>
				</td>
				<?php 
				$qty = $orderItem->getQuantity();
				$prc = $orderItem->getPrice();
				?>
				<td><?php echo $qty; ?></td>
				<td><?php echo '$'.number_format($prc, 2); ?></td>
				<td class="price"><?php echo '$'.number_format($qty*$prc, 2); ?></td>
				<td></td>
			</tr>
			<?php 
			}			
			?>
			<tr>
				<td></td>
				<td colspan="3" ><b>Total</b></td>
				<td class="price"><?php echo '<b>$'.number_format($order->getTotalCost(), 2).'</b>'; ?></td>
				<td></td>
			</tr>
			<tr>
				<td></td>
				<td colspan="3"><i>includes GST of</i></td>
				<td class="price"><?php echo '$'.number_format($order->getGST(), 2); ?></td>
				<td></td>
			</tr>			
		</table>
	
	<?php } ?>

</div>