<div class="container">
	<div class="thumbnail span10">
		<img alt="<?php echo $product->getName(); ?>" style="width: 500px;" src="<?php echo $product->getImageName(); ?>">
		<div class="caption">
		<h4><?php echo $product->getName(); ?></h4>
		<h5>Weight: <?php echo $product->getWeight(); ?> g</h5>
		<h5>Amount in stock: <?php echo $product->getStock(); ?> items</h5>
		<h5>Price: $<?php echo $product->getPrice(); ?> each</h5>
		<p><?php echo $product->getDescription(); ?></p>
		</div>
		<div class="caption">
			<div class="input-append">
				<input class="span1" id="appendedInputButtons" type="text" value="1">
				<button class="btn btn-primary" type="button">Buy</button>
			</div>
		
		<a href="index.php?s=product&p=<?php echo $product->getProductId(); ?>" class="btn btn-primary proButton">More</a>
		</div>
		</div>
</div>

