<div class="container" id="mainContainer">
	<div id="msgContainer"></div>
	<div class="thumbnail span10">
		<img alt="<?php echo $product->getName(); ?>" style="width: 500px;" src="<?php echo $product->getImageName(); ?>">
		<div class="caption">
		<h4><?php echo $product->getName(); ?></h4>
		<h5>Weight: <?php echo $product->getWeight(); ?> g</h5>
		<h5>Amount in stock: <?php echo $product->getStock(); ?> items</h5>
		<h5>Price: $<?php echo $product->getPrice(); ?> each</h5>
		<p><?php echo $product->getDescription(); ?></p>
		</div>
			<?php 
				$pid = $product->getProductId();
				$tbId = "tbBuy".$pid;
				$bId = "bBuy".$pid;
				$getTb = "$('#".$tbId."')";
			?>
		<div class="input-append catButton" id="<?php echo $tbId; ?>div">
			<input class="input-mini text-right" id="<?php echo $tbId; ?>" type="text" value="1">
			<button class="btn btn-primary" id="<?php echo $bId; ?>" type="button" onclick="buyMe(<?php echo $pid; ?>,<?php echo $getTb; ?>)">Buy</button>
		</div>
	</div>
</div>

