<div class="container hero-unit span9">
	<?php if($papers == null){ ?>
	<h3>You are not enrolled in any papers</h3>
	<?php } else { ?>
	<form class="form-inline">
		<div class="control-group">
			<label class="control-label" for="inputPaperNo">Select the paper
				number</label> <select id="inputPaperNo" class="span2">
				<option value="0"> </option>
				<?php foreach($papers as $paper){
					$pID = $paper->getPaperID();
					$numA = $paper->getNumberOfAssigments();
					echo '<option value="'.$pID.":".$numA.'">'.$pID.'</option>';
	  					} ?>
			</select>
		</div>
	</form>
	<hr />
	<div id="radioDiv"></div>
	<hr />
	<form id="fileUploadForm" action="index.php?s=filesubmit" method="post" enctype="multipart/form-data">
		<div class="form-group">
      		<label for="fname">Select a file to upload:</label>
      		<input type="file" id="fname" name="fname">
      		<p class="help-block">Files can only be of the following extensions: *.txt, *.php, *.cpp, *.c, or *.html</p>
		 	<input type="hidden" id="paperNo" name="paperNo" />
		 	<input type="hidden" id="assignmentNo" name="assignmentNo" />
		 	<input type="hidden" id="MAX_FILE_SIZE" name="MAX_FILE_SIZE"  value="2100000"> 
      		<input name="submit" id="uploadSubmit" type="submit" class="btn btn-primary" value="Submit Assignment" />	
    	</div>
	</form>
	<?php } ?>
</div>
