<div class="container" id="mainContainer">

	<h2>Assignment statistics</h2>
	<table class="table table-striped">
		<tr>
			<th>Paper #</th>
			<th>Assignment #</th>
			<th>Submission</th>
			<th>Total Submissions</th>
		</tr>
		<?php foreach($stats as $stat){ ?>		
			<tr>
				<td><?php echo $stat[0]; ?></td>
				<td><?php echo $stat[1]; ?></td>
				<td><?php echo $stat[2]; ?></td>
				<td><?php echo $stat[3]; ?></td>
			</tr>
		<?php } ?>
	</table>



</div>

