<div class="container" id="mainContainer">
<?php include "application/templates/pages/usermenu.phtml";?>
<?php if ($registered=="success"){
	?>

		<h4 class="text-info">Your details have been saved</h4>
		<p>You can return to <a href="index.php?s=userview">My Details</a> or continue <a href="index.php">shopping</a>.</p>
	<?php
} elseif ($registered == "failure"){
	?>
		<h4 class="text-info">We could not save the information</h4>
		<p>Something unexpected happened.</p>
	<?php 
} else {
	?>
		<form action="" method="POST" name="editForm" class="form-horizontal"  id="editForm">
			<h5 class="text-info">Change your password</h5>
			<div class="control-group">
				<label class="control-label" for="password">Password</label>
				<div class="controls">
					<input name="password" type="password" id="fmPassword" placeholder="" class="span3" value="">
					<div id="password-alert"></div>
				</div>
			</div>
			<div class="control-group">
				<label class="control-label" for="confirmPassword">Confirm Password</label>
				<div class="controls">
					<input name="confirmPassword" type="password" id="fmConfirm" placeholder="" class="span3" value="">
					<div id="confirm-alert"></div>
				</div>
			</div>
			<div class="control-group">
				<div class="controls">
					<input name="submit" type="submit" class="btn btn-primary" value="Save">
					<a href="index.php?s=userview" class="btn">Cancel</a>
				</div>
			</div>
			<h5 class="text-info">Update your details</h5>
			<div class="control-group">
				<label class="control-label" for="email">Email</label>
				<div class="controls">
					<input name="email" id="fmEmail" type="text" placeholder="Required" class="span5" value="<?php echo $user->getEmail(); ?>">
					<div id="email-req-alert"></div>
					<div id="email-alert"></div>
				</div>
			</div>
			<div class="control-group">
				<label class="control-label" for="firstname">First Name</label>
				<div class="controls">
					<input name="firstname" id="fmFirstName" type="text" placeholder="Required" class="span5" value="<?php echo $user->getFirstName(); ?>">
					<div id="firstname-req-alert"></div>
					<div id="firstname-alert"></div>
				</div>
			</div>
			<div class="control-group">
				<label class="control-label" for="lastname">Last Name</label>
				<div class="controls">
					<input name="lastname" id="fmLastName" type="text" placeholder="Required" class="span5" value="<?php echo $user->getLastName(); ?>">
					<div id="lastname-req-alert"></div>
					<div id="lastname-alert"></div>
				</div>
			</div>
			<div class="control-group">
				<label class="control-label" for="address1">Address Line 1</label>
				<div class="controls">
					<input name="address1" id="fmAddress1" type="text" placeholder="Required" class="span5" value="<?php echo $user->getAddress1(); ?>">
					<div id="address1-req-alert"></div>
					<div id="address1-alert"></div>
				</div>
			</div>
			<div class="control-group">
				<label class="control-label" for="lastname">Address Line 2</label>
				<div class="controls">
					<input name="address2" id="fmAddress2" type="text" placeholder="" class="span5" value="<?php echo $user->getAddress2(); ?>">
					<div id="address2-alert"></div>
				</div>
			</div>
			<div class="control-group">
				<label class="control-label" for="suburb">Suburb</label>
				<div class="controls">
					<input name="suburb" id="fmSuburb" type="text" placeholder="" class="span3" value="<?php echo $user->getSuburb(); ?>">
					<div id="suburb-alert"></div>
				</div>
			</div>
			<div class="control-group">
				<label class="control-label" for="city">City</label>
				<div class="controls">
					<input name="city" id="fmCity" type="text" placeholder="Required" class="span3" value="<?php echo $user->getCity(); ?>">
					<div id="city-req-alert"></div>
					<div id="city-alert"></div>
				</div>
			</div>
			<div class="control-group">
				<label class="control-label" for="phone">Phone</label>
				<div class="controls">
					<input name="phone" id="fmPhone" type="text" placeholder="" class="span3" value="<?php echo $user->getPhone(); ?>">
					<div id="phone-alert"></div>
				</div>
			</div>
			<div class="control-group">
				<div class="controls">
					<input name="submit" type="submit" class="btn btn-primary" value="Save">
					<a href="index.php?s=userview" class="btn">Cancel</a>
				</div>
			</div>
		</form>
<?php 	
}
?>
</div>






