<?php include "application/templates/pages/usermenu.phtml";?>
<?php if (!$user){
	?>
	<div class="container">
		<h4 class="text-info">Please Login</h4>
		<p>You can <a href="index.php?s=login">Login</a> view your details.</p>
	</div>
	<?php
} else {
	?>
	<div class="container">
		<dl class="dl-horizontal">
  			<dt>Username</dt>
  			<dd><?php echo $user->getUsername(); ?></dd>
		</dl>
		<dl class="dl-horizontal">  			
  			<dt>First Name</dt>
  			<dd><?php echo $user->getFirstName(); ?></dd>
		</dl>
		<dl class="dl-horizontal">  			
  			<dt>Last Name</dt>
  			<dd><?php echo $user->getLastName(); ?></dd>
		</dl>
		<dl class="dl-horizontal">  			
  			<dt>Email</dt>
  			<dd><?php echo $user->getEmail(); ?></dd>
		</dl>
		<dl class="dl-horizontal">  			
  			<dt>Address Line 1</dt>
  			<dd><?php echo $user->getAddress1(); ?></dd>
		</dl>
		<dl class="dl-horizontal">  			
  			<dt>Address Line 2</dt>
  			<dd><?php echo $user->getAddress2(); ?></dd>
		</dl>
		<dl class="dl-horizontal">  			
  			<dt>Suburb</dt>
  			<dd><?php echo $user->getSuburb(); ?></dd>
		</dl>
		<dl class="dl-horizontal">  			
  			<dt>City</dt>
  			<dd><?php echo $user->getCity(); ?></dd>
		</dl>
		<dl class="dl-horizontal">  			
  			<dt>Phone</dt>
  			<dd><?php echo $user->getPhone(); ?></dd>
  		</dl>
		<dl class="dl-horizontal">
  			<dt></dt>
  			<dd><a class="btn btn-primary" href="index.php?s=useredit">Edit</a></dd>
		</dl>
  		
	</div>
<?php 	
}
?>






