<div class="tabbable">
  <ul class="nav nav-tabs">
    <li<?php if($screen=="userview"){echo ' class="active"';}?>><a href="index.php?s=userview">My Details</a></li>
    <li<?php if($screen=="useredit"){echo ' class="active"';}?>><a href="index.php?s=useredit">Edit Details</a></li>
    <li<?php if($screen=="history"){echo ' class="active"';}?>><a href="index.php?s=history">Transaction History</a></li>
  </ul>
</div>



