<div class="row">
	<div class="header-title span7">
		<h1>Sweets Emporium</h1>
	</div>
	<div class="user-info span5 text-right">
		<?php 
			if($user){
				echo "Welcome ".$user->getFirstName();
				echo '  (<a href="index.php?s=userview">My Details</a> / <a href="index.php?s=orderview&amp;p=cart">My Cart</a> / <a href="index.php?s=logout">Logout</a>)';
			} else {
				echo "Welcome Guest ( ";
				echo '<a href="index.php?s=login">Login</a> or ';
				echo '<a href="index.php?s=register">Register</a> )';
			}
		?>
	</div>
</div>
<!-- Navigation -->
<div class="navbar">
	<div class="navbar-inner">
	<ul class="nav">
		<li <?php if($screen=="home"){echo 'class="active"';}?>><a href="index.php">Home</a></li>
		<li <?php if($screen=="category" && $page=="1"){echo 'class="active"';}?>><a href="index.php?s=category&amp;p=1">Lollies</a></li>
		<li <?php if($screen=="category" && $page=="2"){echo 'class="active"';}?>><a href="index.php?s=category&amp;p=2">Cakes</a></li>
		<li <?php if($screen=="category" && $page=="3"){echo 'class="active"';}?>><a href="index.php?s=category&amp;p=3">Muffins</a></li>
		<li <?php if($screen=="category" && $page=="4"){echo 'class="active"';}?>><a href="index.php?s=category&amp;p=4">Biscuits</a></li>
	</ul>
	<div class="input-append searchbox">
		<input class="span2" id="searchBox" type="text">
		<button class="btn" type="button" id="searchButton">Search</button>
	</div>
	<?php
	$numItems = "empty";
	if ($cart){
		$num = $cart->getNumberOfItems();
		if ($num == 1){
			$numItems = "1 item";
		} elseif ($num > 1){
			$numItems = $num." items";
		} 
	}
	 ?>
	<a href="index.php?s=orderview&amp;p=cart" id="cartHeader" class="btn btn cartbox"><i class="icon-shopping-cart"></i> Cart (<?php echo $numItems; ?>)</a>
	</div>
</div>
