<div class="row">
	<div class="header-title span8">
		<h1>Sweets Emporium</h1>
	</div>
	<div class="user-info span4 text-right">
		<?php 
			if($userID){
				echo "User ID: ".$userID;
				echo '  <a href="index.php?s=logout">(Logout)</a>';
			} else {
				echo "Welcome Guest ( ";
				echo '<a href="index.php?s=login">Login</a> or ';
				echo '<a href="index.php?s=register">Register</a> )';
			}
		?>
	</div>
</div>
<!-- Navigation -->
<div class="navbar">
	<div class="navbar-inner">
	<ul class="nav">
		<li <?php if($screen=="home"){echo 'class="active"';}?>><a href="index.php">Home</a></li>
		<li <?php if($screen=="category" && $page=="1"){echo 'class="active"';}?>><a href="index.php?s=category&p=1">Lollies</a></li>
		<li <?php if($screen=="category" && $page=="2"){echo 'class="active"';}?>><a href="index.php?s=category&p=2">Cakes</a></li>
		<li <?php if($screen=="category" && $page=="3"){echo 'class="active"';}?>><a href="index.php?s=category&p=3">Muffins</a></li>
		<li <?php if($screen=="category" && $page=="4"){echo 'class="active"';}?>><a href="index.php?s=category&p=4">Biscuits</a></li>
	</ul>
	<div class="input-append searchbox">
		<input class="span2" id="appendedInputButtons" type="text">
		<button class="btn" type="button">Search</button>
	</div>
	<a href="index.php?s=order&p=current" class="btn btn cartbox"><i class="icon-shopping-cart"></i> Cart (empty)</a>
	</div>
</div>
