<?php 
$screen = (isset($this->viewData["screen"])) ? $this->viewData["screen"] : null;
$page = (isset($this->viewData["page"])) ? $this->viewData["page"] : null;
$user = (isset($this->viewData["user"])) ? $this->viewData["user"] : null; //user object
$cart = (isset($this->viewData["cart"])) ? $this->viewData["cart"] : null; //cart object
$products = (isset($this->viewData["products"])) ? $this->viewData["products"] : null; //product list for category screen
$product = (isset($this->viewData["product"])) ? $this->viewData["product"] : null; //single product for product detail screen
$registered = (isset($this->viewData["registered"])) ? $this->viewData["registered"] : null; //form flag for registeration
$loginTry =  (isset($this->viewData["loginTry"])) ? $this->viewData["loginTry"] : null; //form flag for login
$fmUsername = (isset($this->viewData["fmUsername"])) ? $this->viewData["fmUsername"] : null; //username provided in login
$orderID = (isset($this->viewData["orderID"])) ? $this->viewData["orderID"] : null; //orderID of confirmed Order
$orders = (isset($this->viewData["orders"])) ? $this->viewData["orders"] : null; //list of orders for order history
?>
<!DOCTYPE HTML>
<html lang="en">
	<head>
    	<meta charset="UTF-8">
	    <title>Sweets Emporium - Brent Dykgraaf - ID 00037354</title>
	    <meta name="description" content="Sweets Emporium.">
	    <link href="public/css/bootstrap.min.css" rel="stylesheet" media="screen" type="text/css">
	    <link href="public/css/custom.css" media="screen" rel="stylesheet" type="text/css">
	    <link href="public/css/jquery-ui-1.10.3.custom.min.css" media="screen" rel="stylesheet" type="text/css">
	    <script type="text/javascript" src="public/js/jquery-1.10.2.min.js" ></script>
	    <script type="text/javascript" src="public/js/jquery-ui-1.10.3.custom.min.js" ></script>
	    <script type="text/javascript" src="public/js/bootstrap.min.js" ></script>
	    <script type="text/javascript" src="public/js/asa.js" ></script>
	</head>
	<body>
		<div class="container">
		    <!-- Header -->
			<?php include "application/templates/layout/header.phtml";?>
		    <!-- Main content -->
		    <?php include "application/templates/pages/".$screen.".phtml";?>
		    <!-- Footer -->
			<?php include "application/templates/layout/footer.phtml";?>
		</div>
	</body>
</html>